// Mocks generated by Mockito 5.4.3 from annotations
// in flutter_bloc_fakestoreapi/test/data/datasources/mock_user_data_source.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_bloc_fakestoreapi/data/datasources/user_data_source.dart'
    as _i4;
import 'package:flutter_bloc_fakestoreapi/data/models/auth.dart' as _i2;
import 'package:flutter_bloc_fakestoreapi/data/models/user.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthModel_0 extends _i1.SmartFake implements _i2.AuthModel {
  _FakeAuthModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserModel_1 extends _i1.SmartFake implements _i3.UserModel {
  _FakeUserModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDataSource extends _i1.Mock implements _i4.UserDataSource {
  @override
  _i5.Future<_i2.AuthModel> userLogin(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #userLogin,
          [
            email,
            password,
          ],
        ),
        returnValue: _i5.Future<_i2.AuthModel>.value(_FakeAuthModel_0(
          this,
          Invocation.method(
            #userLogin,
            [
              email,
              password,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.AuthModel>.value(_FakeAuthModel_0(
          this,
          Invocation.method(
            #userLogin,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i2.AuthModel>);

  @override
  _i5.Future<_i3.UserModel> userDetail(int? id) => (super.noSuchMethod(
        Invocation.method(
          #userDetail,
          [id],
        ),
        returnValue: _i5.Future<_i3.UserModel>.value(_FakeUserModel_1(
          this,
          Invocation.method(
            #userDetail,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.UserModel>.value(_FakeUserModel_1(
          this,
          Invocation.method(
            #userDetail,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.UserModel>);
}
