name: flutter_bloc_fakestoreapi
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  badges: ^3.1.2
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  get_it: ^7.6.4
  go_router: ^12.1.1
  http: ^1.1.0
  intl: ^0.18.1
  jwt_decoder: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.3

flutter:
  uses-material-design: true
  assets:
    - assets/
