// Mocks generated by Mockito 5.4.3 from annotations
// in flutter_bloc_fakestoreapi/test/domain/usecases/mock_user_repository.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_bloc_fakestoreapi/core/errors/server_failure.dart'
    as _i5;
import 'package:flutter_bloc_fakestoreapi/domain/entities/auth.dart' as _i6;
import 'package:flutter_bloc_fakestoreapi/domain/entities/users.dart' as _i7;
import 'package:flutter_bloc_fakestoreapi/domain/repositories/user_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i3.UserRepository {
  @override
  _i4.Future<_i2.Either<_i5.ServerFailure, _i6.AuthEntity>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.ServerFailure, _i6.AuthEntity>>.value(
                _FakeEither_0<_i5.ServerFailure, _i6.AuthEntity>(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.ServerFailure, _i6.AuthEntity>>.value(
                _FakeEither_0<_i5.ServerFailure, _i6.AuthEntity>(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.ServerFailure, _i6.AuthEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.ServerFailure, _i7.UserEntity>> userDetail() =>
      (super.noSuchMethod(
        Invocation.method(
          #userDetail,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.ServerFailure, _i7.UserEntity>>.value(
                _FakeEither_0<_i5.ServerFailure, _i7.UserEntity>(
          this,
          Invocation.method(
            #userDetail,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.ServerFailure, _i7.UserEntity>>.value(
                _FakeEither_0<_i5.ServerFailure, _i7.UserEntity>(
          this,
          Invocation.method(
            #userDetail,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.ServerFailure, _i7.UserEntity>>);
}
